### ISSUE TITLE
"gatsby build" error,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [scottnonnenberg/blog#2]
hi.

```
root@AR:/usr/local/blog.scottnonnenberg.com# gatsby build
Generating CSS
Generating Static HTML
Failed at generating HTML

/usr/local/blog.scottnonnenberg.com/node_modules/gatsby/dist/bin/cli.js:52
      throw err;
      ^
Error: Error: no window object present
    at render-page.js:52193:16
    at Object.exports.EventEmitter._events (render-page.js:52225:4)
    at __webpack_require__ (render-page.js:30:30)
    at Object.http (render-page.js:52121:13)
    at __webpack_require__ (render-page.js:30:30)
    at Object.<anonymous> (render-page.js:49666:14)
    at Object.<anonymous> (render-page.js:50114:31)
    at __webpack_require__ (render-page.js:30:30)
    at Object.<anonymous> (render-page.js:49344:13)
    at __webpack_require__ (render-page.js:30:30)
root@AR:/usr/local/blog.scottnonnenberg.com#
```

thanks

**Comment by scottnonnenberg** [comment]
Can you tell me how you installed `gatsby` in your project? Please also give me the output of `npm ls gatsby` in the project.

**Comment by luckypoem** [comment]
hi.

npm install -g gatsby,then in my project i also run:
npm install --save gatsby

root@AR:/usr/local/blog.scottnonnenberg.com# npm ls gatsby
blog-scottnonnenberg-com@0.11.0 /usr/local/blog.scottnonnenberg.com
└── gatsby@0.12.5 
root@AR:/usr/local/blog.scottnonnenberg.com#

thanks

**Comment by scottnonnenberg** [comment]
This project is compatible only with `gatsby@0.11.3` for now, specifically my fork of it. Please follow the directions in the readme: https://github.com/scottnonnenberg/blog#forking-gatsby (pull that project down and run `npm link` in that directory, then run `npm link gatsby` in the blog project).

Soon enough this will no longer be required, but for now it's a couple of extra required steps.

**Comment by luckypoem** [comment]
hi.

still encounter errors running the extra required steps.
expect that u can update the repo to use the latest gatsby.

**Comment by scottnonnenberg** [comment]
In the near term, to dig into this problem yourself, you can look for what generates the 'no window object present' error. It doesn't seem like `gatsby` does, looking at its most recent source code.
