### ISSUE TITLE
npm create posts

### ISSUE THREAD

**Issue by btotharye** [scottnonnenberg/blog#5]
when trying to do npm run make-post I get the below:

var previousPath = previous.data.path;

Should this work or do I have to give it something else with the command besides just the title?

Thanks

**Comment by scottnonnenberg** [comment]
If you've deleted all posts and are starting fresh, the script might not work as expected. :0)

**Comment by btotharye** [comment]
yea thats what it was once I created a new post it started working, thanks.  This is a good starting point for getting my new blog going without having to do it all from scratch.

Thanks
