### ISSUE TITLE
Deploy with Netifly

### ISSUE THREAD

**Issue by btotharye** [scottnonnenberg/blog#6]
I know from your instructions it mentioned adding in the mailchimp and piwki.js files which I did and this builds locally fine but when trying to build it on Netifly its failing cause of piwik and such, is this normal or a way to get around it until I set that up?

The weird thing is I don't get any errors on local build only when using Netifly:

```
Failed at generating HTML
1:55:41 PM: /opt/build/repo/node_modules/gatsby/dist/bin/cli.js:52
1:55:41 PM:       throw err;
1:55:41 PM:       ^
1:55:41 PM: Error: ./~/httpreq/lib/httpreq.js
1:55:41 PM: Module not found: Error: Cannot resolve module 'fs' in /opt/build/repo/node_modules/httpreq/lib
1:55:41 PM: resolve module fs in /opt/build/repo/node_modules/httpreq/lib
1:55:41 PM:   looking for modules in /opt/build/repo
1:55:41 PM:     /opt/build/repo/fs doesn't exist (module as directory)
1:55:41 PM:     resolve 'file' fs in /opt/build/repo
1:55:41 PM:       resolve file
1:55:41 PM:         /opt/build/repo/fs doesn't exist
1:55:41 PM:         /opt/build/repo/fs.js doesn't exist
1:55:41 PM:         /opt/build/repo/fs.jsx doesn't exist
1:55:41 PM:         /opt/build/repo/fs.cjsx doesn't exist
1:55:41 PM:         /opt/build/repo/fs.coffee doesn't exist
1:55:41 PM:         /opt/build/repo/fs.json doesn't exist
1:55:41 PM:         /opt/build/repo/fs.less doesn't exist
1:55:41 PM:         /opt/build/repo/fs.css doesn't exist
1:55:41 PM:         /opt/build/repo/fs.scss doesn't exist
1:55:41 PM:         /opt/build/repo/fs.sass doesn't exist
1:55:41 PM:         /opt/build/repo/fs.toml doesn't exist
1:55:41 PM:         /opt/build/repo/fs.yaml doesn't exist
```

**Comment by scottnonnenberg** [comment]
Hm. I haven't used Netlify at all, so I'm not sure what's going on. But I do know that what I'm seeing in that error is that you don't have access to the `fs` node module. Doesn't seem to have anything to do with piwik/mailchimp stuff.

**Comment by btotharye** [comment]
ok was just making sure cause those are below this one talking about the files missing just thought I would ask I'm gonna try to figure out what is going on, could be on Netlify's end.  My other gatsby project builds fine in Netifly though.

**Comment by scottnonnenberg** [comment]
Note: This project is using a pretty old version of gatsby.
